# YOLOv7n Configuration for Mezzopiano Detection
# Lightweight version optimized for single class detection

name: v7n-mezzopiano
anchor:
  reg_max: 16
  strides: [8, 16, 32]

model:
  # YOLOv7n Nano Architecture - Optimized for speed
  backbone:
    - Conv:
        args: {out_channels: 32, kernel_size: 3, stride: 2}
        source: 0
    - Conv:
        args: {out_channels: 64, kernel_size: 3, stride: 2}
    - RepNCSPELAN:
        args: {out_channels: 128, part_channels: 64}
    - ADown:
        args: {out_channels: 128}
    - RepNCSPELAN:
        args: {out_channels: 256, part_channels: 128}
        tags: B3
    - ADown:
        args: {out_channels: 256}
    - RepNCSPELAN:
        args: {out_channels: 384, part_channels: 192}
        tags: B4
    - ADown:
        args: {out_channels: 384}
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 256}
        tags: B5

  neck:
    - SPPELAN:
        args: {out_channels: 512}
        tags: N3
    - UpSample:
        args: {scale_factor: 2, mode: nearest}
    - Concat:
        source: [-1, B4]
    - RepNCSPELAN:
        args: {out_channels: 384, part_channels: 192}
        tags: N4
    - UpSample:
        args: {scale_factor: 2, mode: nearest}
    - Concat:
        source: [-1, B3]

  head:
    - RepNCSPELAN:
        args: {out_channels: 256, part_channels: 128}
        tags: P3
    - ADown:
        args: {out_channels: 256}
    - Concat:
        source: [-1, N4]
    - RepNCSPELAN:
        args: {out_channels: 384, part_channels: 192}
        tags: P4
    - ADown:
        args: {out_channels: 384}
    - Concat:
        source: [-1, N3]
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 256}
        tags: P5

  detection:
    - MultiheadDetection:
        source: [P3, P4, P5]
        tags: Main
        output: true